export const LOVE_ITEMS = [
  'your anger',
  'your small belly',
  'your eyes',
  'your voice',
  'the little noises you make',
  'your laugh',
  'the way you laugh at your own jokes first',
  'your stubbornness',
  'how you scold me and still worry',
  'your handwriting',
  'the way you say my name',
  'your sleepy morning voice',
  'how you get excited over small things',
  'your competitive side',
  'how you never actually stay mad for long',
  'your messy hair right after you wake up',
  "the way you walk fast when you're annoyed",
  'your patience with me',
  'how you remember tiny details I forget',
  "your honesty, even when it's blunt",
  'the way you care for everyone around you',
  'your food taste, questionable as it is',
  'how you overthink everything',
  'your voice notes that go on forever',
  'the way you type in all caps when excited',
  'your emoji spam',
  'how you plan everything down to the minute',
  'your midnight cravings',
  'the way you hum without noticing',
  'your dramatic reactions',
  'how you say certain words in your own way',
  'your accent on English words',
  "the way you dance like no one's watching",
  'your off-key singing',
  'how shy you get when someone compliments you',
  'your protective side',
  'how jealous you get, even when you deny it',
  "the way you forgive, even when it's hard",
  'your prayers for me',
  'how you never give up on us',
  'your support during my exams',
  "the faces you make when you're annoyed",
  'your competitive face during games',
  'how seriously you take Ludo',
  'your fashion sense',
  'how you match your outfits to your mood',
  "the way you tie your hair up when you're focused",
  'your handwriting on little notes',
  'how you text good morning even when busy',
  'the way you check on me without saying much',
  'your loyalty',
  'how you defend me without me even asking',
  'your kindness to strangers',
  'how you treat animals',
  "your smile when you're actually happy",
  'the dimple that shows up sometimes',
  'your height — short and mighty',
  'how you tiptoe to reach things',
  'your hands',
  'the way you hold my hand',
  'how warm your hugs are',
  'your forehead kisses',
  'the way you fall asleep mid-conversation',
  'the snoring you deny having',
  'how you steal my hoodie',
  'your side of every argument',
  'how you always make up first',
  'the way you say sorry without saying sorry',
  'your resting serious face',
  'how soft you get once you trust someone',
  'your childhood stories',
  'the way you talk about your family',
  'how much you love your friends',
  'your loyalty to people who matter',
  'the way you get nostalgic over old photos',
  'how you save every little memory',
  'your playlist choices',
  'the songs you play on repeat',
  'how you cry at movies and deny it after',
  'your competitive streak in exams',
  'how hard you study, even when tired',
  'your handwritten notes before exams',
  'the way you explain things patiently',
  'how you never let me give up',
  "your belief in me, even when I don't have it myself",
  'the way you say "naa iruken" and mean it',
  'how safe your presence feels',
  'your calm in my chaos',
  'the way you ground me',
  'how home feels like wherever you are',
  'your quiet strength',
  'how you carry more than you show',
  'the softness under all that toughness',
  'your scent, familiar and calming',
  'your innocence',
  'the little things you do without realizing',
  'how you make ordinary days feel like something',
  "every version of you I've known so far",
  'simply, you — all of it, still',
]
